# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
  vendor/htc/glacier/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
  vendor/htc/glacier/proprietary/etc/A1026_CFG.csv:system/etc/A1026_CFG.csv \
  vendor/htc/glacier/proprietary/etc/AdieHWCodec.csv:system/etc/AdieHWCodec.csv \
  vendor/htc/glacier/proprietary/etc/AdieHWCodec_WA.csv:system/etc/AdieHWCodec_WA.csv \
  vendor/htc/glacier/proprietary/etc/agps_rm:system/etc/agps_rm \
  vendor/htc/glacier/proprietary/etc/AudioBTID.csv:system/etc/AudioBTID.csv \
  vendor/htc/glacier/proprietary/etc/TPA2051_CFG.csv:system/etc/TPA2051_CFG.csv \
  vendor/htc/glacier/proprietary/etc/vpimg:system/etc/vpimg \
  vendor/htc/glacier/proprietary/etc/firmware/audio_cal_BOV1_7.acdb:system/etc/firmware/audio_cal_BOV1_7.acdb \
  vendor/htc/glacier/proprietary/etc/firmware/Glacier_SPK.acdb:system/etc/firmware/Glacier_SPK.acdb \
  vendor/htc/glacier/proprietary/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
  vendor/htc/glacier/proprietary/etc/firmware/BCM4329B1_002.002.023.0589.0632.hcd:system/etc/firmware/BCM4329B1_002.002.023.0589.0632.hcd \
  vendor/htc/glacier/proprietary/etc/firmware/default.acdb:system/etc/firmware/default.acdb \
  vendor/htc/glacier/proprietary/etc/firmware/default.acdb:system/etc/firmware/default_mfg.acdb \
  vendor/htc/glacier/proprietary/etc/firmware/default_org.acdb:system/etc/firmware/default_org.acdb \
  vendor/htc/glacier/proprietary/etc/firmware/default_org_WA.acdb:system/etc/firmware/default_org_WA.acdb \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
  vendor/htc/glacier/proprietary/etc/firmware/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
  vendor/htc/glacier/proprietary/etc/firmware/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \
  vendor/htc/glacier/proprietary/etc/firmware/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \
  vendor/htc/glacier/proprietary/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
  vendor/htc/glacier/proprietary/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
  vendor/htc/glacier/proprietary/bin/akmd:system/bin/akmd \
  vendor/htc/glacier/proprietary/bin/awb_camera:system/bin/awb_camera \
  vendor/htc/glacier/proprietary/bin/bma150_usr:system/bin/bma150_usr \
  vendor/htc/glacier/proprietary/bin/lsc_camera:system/bin/lsc_camera \
  vendor/htc/glacier/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/htc/glacier/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/htc/glacier/proprietary/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
  vendor/htc/glacier/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
  vendor/htc/glacier/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/htc/glacier/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/glacier/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/glacier/proprietary/lib/drm/libdrmwvmplugin.so:/system/lib/drm/libdrmwvmplugin.so \
  vendor/htc/glacier/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/glacier/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/glacier/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/glacier/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/glacier/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
  vendor/htc/glacier/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/glacier/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
  vendor/htc/glacier/proprietary/lib/libwvm.so:system/lib/libwvm.so \
  vendor/htc/glacier/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
  vendor/htc/glacier/proprietary/lib/libchromatix_s5k4e1gx_default_video.so:system/lib/libchromatix_s5k4e1gx_default_video.so \
  vendor/htc/glacier/proprietary/lib/libchromatix_s5k4e1gx_preview.so:system/lib/libchromatix_s5k4e1gx_preview.so \
  vendor/htc/glacier/proprietary/lib/libv8.so:system/lib/libv8.so \
  vendor/htc/glacier/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/htc/glacier/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/htc/glacier/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/htc/glacier/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
  vendor/htc/glacier/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
  vendor/htc/glacier/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/htc/glacier/proprietary/lib/libhtc_ril.so:system/lib/libhtc_ril.so \
  vendor/htc/glacier/proprietary/lib/egl/egl.cfg:/system/lib/egl/egl.cfg \
  vendor/htc/glacier/proprietary/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
  vendor/htc/glacier/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
  vendor/htc/glacier/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libGLESv2S3D_adreno200.so:/system/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/htc/glacier/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/glacier/proprietary/lib/libC2D2.so:/system/lib/libC2D2.so \
  vendor/htc/glacier/proprietary/lib/libc2d2_z180.so:/system/lib/libc2d2_z180.so \
  vendor/htc/glacier/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
  vendor/htc/glacier/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so \
  vendor/htc/glacier/proprietary/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so
